/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TunevioRouteImport } from './routes/tunevio'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StreamStudioRouteImport } from './routes/stream-studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as OffTheBlockRouteImport } from './routes/off-the-block'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MicDropRouteImport } from './routes/mic-drop'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CreatorAgreementRouteImport } from './routes/creator-agreement'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ArtistSubmissionRouteImport } from './routes/artist-submission'
import { Route as ArtistDashboardRouteImport } from './routes/artist-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as TrackSlugRouteImport } from './routes/track.$slug'
import { Route as StreamRoomRouteImport } from './routes/stream.$room'
import { Route as StageRoomIdRouteImport } from './routes/stage.$roomId'
import { Route as SettingsSocialLinksRouteImport } from './routes/settings.social-links'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMusicMediaRouteImport } from './routes/settings.music-media'
import { Route as SettingsMerchRouteImport } from './routes/settings.merch'
import { Route as SettingsMembershipRouteImport } from './routes/settings.membership'
import { Route as SettingsEventsRouteImport } from './routes/settings.events'
import { Route as SettingsConnectedAppsRouteImport } from './routes/settings.connected-apps'
import { Route as SettingsBroadcastHelpRouteImport } from './routes/settings.broadcast-help'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsArtistInfoRouteImport } from './routes/settings.artist-info'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as PlayRanksRouteImport } from './routes/play.ranks'
import { Route as PlayRoomRouteImport } from './routes/play.$room'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as BroadcastBroadcastIdRouteImport } from './routes/broadcast.$broadcastId'
import { Route as BlogLiveStreamMusicTwitchYoutubeFacebookRouteImport } from './routes/blog.live-stream-music-twitch-youtube-facebook'
import { Route as BlogHowToLiveStreamMusicRouteImport } from './routes/blog.how-to-live-stream-music'
import { Route as BlogHowArtistsGetPaidForStreamingMusicRouteImport } from './routes/blog.how-artists-get-paid-for-streaming-music'
import { Route as BlogCanYouPlayMusicOnLiveStreamRouteImport } from './routes/blog.can-you-play-music-on-live-stream'
import { Route as ArtistUpgradeRouteImport } from './routes/artist.upgrade'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AdminVoteAttemptsRouteImport } from './routes/admin.vote-attempts'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStudioBookingsRouteImport } from './routes/admin.studio-bookings'
import { Route as AdminStreamsRouteImport } from './routes/admin.streams'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMerchRouteImport } from './routes/admin.merch'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCancellationEmailsRouteImport } from './routes/admin.cancellation-emails'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlockBookingsRouteImport } from './routes/admin.block-bookings'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as PlayAudienceRoomRouteImport } from './routes/play.audience.$room'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BroadcastBroadcastIdManageRouteImport } from './routes/broadcast.$broadcastId.manage'
import { Route as ApiPublicStudioBookingRouteImport } from './routes/api/public/studio-booking'
import { Route as ApiPublicCheckoutCancellationEmailRouteImport } from './routes/api/public/checkout-cancellation-email'
import { Route as ApiPublicBlockBookingRouteImport } from './routes/api/public/block-booking'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify/webhook'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProcessPayoutsRouteImport } from './routes/api/public/hooks/process-payouts'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TunevioRoute = TunevioRouteImport.update({
  id: '/tunevio',
  path: '/tunevio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamStudioRoute = StreamStudioRouteImport.update({
  id: '/stream-studio',
  path: '/stream-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OffTheBlockRoute = OffTheBlockRouteImport.update({
  id: '/off-the-block',
  path: '/off-the-block',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MicDropRoute = MicDropRouteImport.update({
  id: '/mic-drop',
  path: '/mic-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAgreementRoute = CreatorAgreementRouteImport.update({
  id: '/creator-agreement',
  path: '/creator-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSubmissionRoute = ArtistSubmissionRouteImport.update({
  id: '/artist-submission',
  path: '/artist-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistDashboardRoute = ArtistDashboardRouteImport.update({
  id: '/artist-dashboard',
  path: '/artist-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSlugRoute = TrackSlugRouteImport.update({
  id: '/track/$slug',
  path: '/track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoomRoute = StreamRoomRouteImport.update({
  id: '/stream/$room',
  path: '/stream/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const StageRoomIdRoute = StageRoomIdRouteImport.update({
  id: '/stage/$roomId',
  path: '/stage/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSocialLinksRoute = SettingsSocialLinksRouteImport.update({
  id: '/social-links',
  path: '/social-links',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMusicMediaRoute = SettingsMusicMediaRouteImport.update({
  id: '/music-media',
  path: '/music-media',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMerchRoute = SettingsMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMembershipRoute = SettingsMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEventsRoute = SettingsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectedAppsRoute = SettingsConnectedAppsRouteImport.update({
  id: '/connected-apps',
  path: '/connected-apps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBroadcastHelpRoute = SettingsBroadcastHelpRouteImport.update({
  id: '/broadcast-help',
  path: '/broadcast-help',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArtistInfoRoute = SettingsArtistInfoRouteImport.update({
  id: '/artist-info',
  path: '/artist-info',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const PlayRanksRoute = PlayRanksRouteImport.update({
  id: '/play/ranks',
  path: '/play/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomRoute = PlayRoomRouteImport.update({
  id: '/play/$room',
  path: '/play/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastBroadcastIdRoute = BroadcastBroadcastIdRouteImport.update({
  id: '/broadcast/$broadcastId',
  path: '/broadcast/$broadcastId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLiveStreamMusicTwitchYoutubeFacebookRoute =
  BlogLiveStreamMusicTwitchYoutubeFacebookRouteImport.update({
    id: '/blog/live-stream-music-twitch-youtube-facebook',
    path: '/blog/live-stream-music-twitch-youtube-facebook',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToLiveStreamMusicRoute =
  BlogHowToLiveStreamMusicRouteImport.update({
    id: '/blog/how-to-live-stream-music',
    path: '/blog/how-to-live-stream-music',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowArtistsGetPaidForStreamingMusicRoute =
  BlogHowArtistsGetPaidForStreamingMusicRouteImport.update({
    id: '/blog/how-artists-get-paid-for-streaming-music',
    path: '/blog/how-artists-get-paid-for-streaming-music',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCanYouPlayMusicOnLiveStreamRoute =
  BlogCanYouPlayMusicOnLiveStreamRouteImport.update({
    id: '/blog/can-you-play-music-on-live-stream',
    path: '/blog/can-you-play-music-on-live-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtistUpgradeRoute = ArtistUpgradeRouteImport.update({
  id: '/artist/upgrade',
  path: '/artist/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoteAttemptsRoute = AdminVoteAttemptsRouteImport.update({
  id: '/vote-attempts',
  path: '/vote-attempts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioBookingsRoute = AdminStudioBookingsRouteImport.update({
  id: '/studio-bookings',
  path: '/studio-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStreamsRoute = AdminStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchRoute = AdminMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancellationEmailsRoute = AdminCancellationEmailsRouteImport.update({
  id: '/cancellation-emails',
  path: '/cancellation-emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlockBookingsRoute = AdminBlockBookingsRouteImport.update({
  id: '/block-bookings',
  path: '/block-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayAudienceRoomRoute = PlayAudienceRoomRouteImport.update({
  id: '/play/audience/$room',
  path: '/play/audience/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastBroadcastIdManageRoute =
  BroadcastBroadcastIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => BroadcastBroadcastIdRoute,
  } as any)
const ApiPublicStudioBookingRoute = ApiPublicStudioBookingRouteImport.update({
  id: '/api/public/studio-booking',
  path: '/api/public/studio-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutCancellationEmailRoute =
  ApiPublicCheckoutCancellationEmailRouteImport.update({
    id: '/api/public/checkout-cancellation-email',
    path: '/api/public/checkout-cancellation-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlockBookingRoute = ApiPublicBlockBookingRouteImport.update({
  id: '/api/public/block-booking',
  path: '/api/public/block-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify/webhook',
  path: '/api/public/shopify/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessPayoutsRoute =
  ApiPublicHooksProcessPayoutsRouteImport.update({
    id: '/api/public/hooks/process-payouts',
    path: '/api/public/hooks/process-payouts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-submission': typeof ArtistSubmissionRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/tunevio': typeof TunevioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$slug': typeof ASlugRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/block-bookings': typeof AdminBlockBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/studio-bookings': typeof AdminStudioBookingsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-attempts': typeof AdminVoteAttemptsRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/blog/can-you-play-music-on-live-stream': typeof BlogCanYouPlayMusicOnLiveStreamRoute
  '/blog/how-artists-get-paid-for-streaming-music': typeof BlogHowArtistsGetPaidForStreamingMusicRoute
  '/blog/how-to-live-stream-music': typeof BlogHowToLiveStreamMusicRoute
  '/blog/live-stream-music-twitch-youtube-facebook': typeof BlogLiveStreamMusicTwitchYoutubeFacebookRoute
  '/broadcast/$broadcastId': typeof BroadcastBroadcastIdRouteWithChildren
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/invite/$code': typeof InviteCodeRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/play/ranks': typeof PlayRanksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/broadcast-help': typeof SettingsBroadcastHelpRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stage/$roomId': typeof StageRoomIdRoute
  '/stream/$room': typeof StreamRoomRoute
  '/track/$slug': typeof TrackSlugRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/play/': typeof PlayIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/broadcast/$broadcastId/manage': typeof BroadcastBroadcastIdManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/hooks/process-payouts': typeof ApiPublicHooksProcessPayoutsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-submission': typeof ArtistSubmissionRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/tunevio': typeof TunevioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$slug': typeof ASlugRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/block-bookings': typeof AdminBlockBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/studio-bookings': typeof AdminStudioBookingsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-attempts': typeof AdminVoteAttemptsRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/blog/can-you-play-music-on-live-stream': typeof BlogCanYouPlayMusicOnLiveStreamRoute
  '/blog/how-artists-get-paid-for-streaming-music': typeof BlogHowArtistsGetPaidForStreamingMusicRoute
  '/blog/how-to-live-stream-music': typeof BlogHowToLiveStreamMusicRoute
  '/blog/live-stream-music-twitch-youtube-facebook': typeof BlogLiveStreamMusicTwitchYoutubeFacebookRoute
  '/broadcast/$broadcastId': typeof BroadcastBroadcastIdRouteWithChildren
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/invite/$code': typeof InviteCodeRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/play/ranks': typeof PlayRanksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/broadcast-help': typeof SettingsBroadcastHelpRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stage/$roomId': typeof StageRoomIdRoute
  '/stream/$room': typeof StreamRoomRoute
  '/track/$slug': typeof TrackSlugRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/play': typeof PlayIndexRoute
  '/videos': typeof VideosIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/broadcast/$broadcastId/manage': typeof BroadcastBroadcastIdManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/hooks/process-payouts': typeof ApiPublicHooksProcessPayoutsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-submission': typeof ArtistSubmissionRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/payouts': typeof PayoutsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/tunevio': typeof TunevioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$slug': typeof ASlugRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/block-bookings': typeof AdminBlockBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/studio-bookings': typeof AdminStudioBookingsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vote-attempts': typeof AdminVoteAttemptsRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/blog/can-you-play-music-on-live-stream': typeof BlogCanYouPlayMusicOnLiveStreamRoute
  '/blog/how-artists-get-paid-for-streaming-music': typeof BlogHowArtistsGetPaidForStreamingMusicRoute
  '/blog/how-to-live-stream-music': typeof BlogHowToLiveStreamMusicRoute
  '/blog/live-stream-music-twitch-youtube-facebook': typeof BlogLiveStreamMusicTwitchYoutubeFacebookRoute
  '/broadcast/$broadcastId': typeof BroadcastBroadcastIdRouteWithChildren
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/invite/$code': typeof InviteCodeRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/play/ranks': typeof PlayRanksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/broadcast-help': typeof SettingsBroadcastHelpRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stage/$roomId': typeof StageRoomIdRoute
  '/stream/$room': typeof StreamRoomRoute
  '/track/$slug': typeof TrackSlugRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/play/': typeof PlayIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/broadcast/$broadcastId/manage': typeof BroadcastBroadcastIdManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/hooks/process-payouts': typeof ApiPublicHooksProcessPayoutsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/artist-dashboard'
    | '/artist-submission'
    | '/artists'
    | '/contact'
    | '/cookie-policy'
    | '/creator-agreement'
    | '/credits'
    | '/dashboard'
    | '/deck'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/network'
    | '/notifications'
    | '/off-the-block'
    | '/payouts'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/terms'
    | '/trending'
    | '/tunevio'
    | '/unsubscribe'
    | '/a/$slug'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/block-bookings'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/studio-bookings'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vote-attempts'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/blog/can-you-play-music-on-live-stream'
    | '/blog/how-artists-get-paid-for-streaming-music'
    | '/blog/how-to-live-stream-music'
    | '/blog/live-stream-music-twitch-youtube-facebook'
    | '/broadcast/$broadcastId'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/genre/$slug'
    | '/invite/$code'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/play/ranks'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/broadcast-help'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stage/$roomId'
    | '/stream/$room'
    | '/track/$slug'
    | '/user/$id'
    | '/videos/$id'
    | '/admin/'
    | '/blog/'
    | '/play/'
    | '/videos/'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/broadcast/$broadcastId/manage'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/hooks/process-payouts'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/artist-dashboard'
    | '/artist-submission'
    | '/artists'
    | '/contact'
    | '/cookie-policy'
    | '/creator-agreement'
    | '/credits'
    | '/dashboard'
    | '/deck'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/network'
    | '/notifications'
    | '/off-the-block'
    | '/payouts'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/terms'
    | '/trending'
    | '/tunevio'
    | '/unsubscribe'
    | '/a/$slug'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/block-bookings'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/studio-bookings'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vote-attempts'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/blog/can-you-play-music-on-live-stream'
    | '/blog/how-artists-get-paid-for-streaming-music'
    | '/blog/how-to-live-stream-music'
    | '/blog/live-stream-music-twitch-youtube-facebook'
    | '/broadcast/$broadcastId'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/genre/$slug'
    | '/invite/$code'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/play/ranks'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/broadcast-help'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stage/$roomId'
    | '/stream/$room'
    | '/track/$slug'
    | '/user/$id'
    | '/videos/$id'
    | '/admin'
    | '/blog'
    | '/play'
    | '/videos'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/broadcast/$broadcastId/manage'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/hooks/process-payouts'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/artist-dashboard'
    | '/artist-submission'
    | '/artists'
    | '/contact'
    | '/cookie-policy'
    | '/creator-agreement'
    | '/credits'
    | '/dashboard'
    | '/deck'
    | '/discover'
    | '/dmca'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/network'
    | '/notifications'
    | '/off-the-block'
    | '/payouts'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/terms'
    | '/trending'
    | '/tunevio'
    | '/unsubscribe'
    | '/a/$slug'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/block-bookings'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/studio-bookings'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vote-attempts'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/blog/can-you-play-music-on-live-stream'
    | '/blog/how-artists-get-paid-for-streaming-music'
    | '/blog/how-to-live-stream-music'
    | '/blog/live-stream-music-twitch-youtube-facebook'
    | '/broadcast/$broadcastId'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/genre/$slug'
    | '/invite/$code'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/play/ranks'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/broadcast-help'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stage/$roomId'
    | '/stream/$room'
    | '/track/$slug'
    | '/user/$id'
    | '/videos/$id'
    | '/admin/'
    | '/blog/'
    | '/play/'
    | '/videos/'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/broadcast/$broadcastId/manage'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/hooks/process-payouts'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistDashboardRoute: typeof ArtistDashboardRoute
  ArtistSubmissionRoute: typeof ArtistSubmissionRoute
  ArtistsRoute: typeof ArtistsRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CreatorAgreementRoute: typeof CreatorAgreementRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  DeckRoute: typeof DeckRoute
  DiscoverRoute: typeof DiscoverRoute
  DmcaRoute: typeof DmcaRoute
  EarningsRoute: typeof EarningsRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MicDropRoute: typeof MicDropRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  OffTheBlockRoute: typeof OffTheBlockRoute
  PayoutsRoute: typeof PayoutsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecordingsRoute: typeof RecordingsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreamStudioRoute: typeof StreamStudioRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  TunevioRoute: typeof TunevioRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ASlugRoute: typeof ASlugRoute
  ArtistIdRoute: typeof ArtistIdRoute
  ArtistUpgradeRoute: typeof ArtistUpgradeRoute
  BlogCanYouPlayMusicOnLiveStreamRoute: typeof BlogCanYouPlayMusicOnLiveStreamRoute
  BlogHowArtistsGetPaidForStreamingMusicRoute: typeof BlogHowArtistsGetPaidForStreamingMusicRoute
  BlogHowToLiveStreamMusicRoute: typeof BlogHowToLiveStreamMusicRoute
  BlogLiveStreamMusicTwitchYoutubeFacebookRoute: typeof BlogLiveStreamMusicTwitchYoutubeFacebookRoute
  BroadcastBroadcastIdRoute: typeof BroadcastBroadcastIdRouteWithChildren
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GenreSlugRoute: typeof GenreSlugRoute
  InviteCodeRoute: typeof InviteCodeRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  PayReturnRoute: typeof PayReturnRoute
  PlayRoomRoute: typeof PlayRoomRoute
  PlayRanksRoute: typeof PlayRanksRoute
  StageRoomIdRoute: typeof StageRoomIdRoute
  StreamRoomRoute: typeof StreamRoomRoute
  TrackSlugRoute: typeof TrackSlugRoute
  UserIdRoute: typeof UserIdRoute
  VideosIdRoute: typeof VideosIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  ApiPublicBlockBookingRoute: typeof ApiPublicBlockBookingRoute
  ApiPublicCheckoutCancellationEmailRoute: typeof ApiPublicCheckoutCancellationEmailRoute
  ApiPublicStudioBookingRoute: typeof ApiPublicStudioBookingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PlayAudienceRoomRoute: typeof PlayAudienceRoomRoute
  ApiPublicHooksProcessPayoutsRoute: typeof ApiPublicHooksProcessPayoutsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tunevio': {
      id: '/tunevio'
      path: '/tunevio'
      fullPath: '/tunevio'
      preLoaderRoute: typeof TunevioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream-studio': {
      id: '/stream-studio'
      path: '/stream-studio'
      fullPath: '/stream-studio'
      preLoaderRoute: typeof StreamStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-the-block': {
      id: '/off-the-block'
      path: '/off-the-block'
      fullPath: '/off-the-block'
      preLoaderRoute: typeof OffTheBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mic-drop': {
      id: '/mic-drop'
      path: '/mic-drop'
      fullPath: '/mic-drop'
      preLoaderRoute: typeof MicDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-agreement': {
      id: '/creator-agreement'
      path: '/creator-agreement'
      fullPath: '/creator-agreement'
      preLoaderRoute: typeof CreatorAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-submission': {
      id: '/artist-submission'
      path: '/artist-submission'
      fullPath: '/artist-submission'
      preLoaderRoute: typeof ArtistSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-dashboard': {
      id: '/artist-dashboard'
      path: '/artist-dashboard'
      fullPath: '/artist-dashboard'
      preLoaderRoute: typeof ArtistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$slug': {
      id: '/track/$slug'
      path: '/track/$slug'
      fullPath: '/track/$slug'
      preLoaderRoute: typeof TrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$room': {
      id: '/stream/$room'
      path: '/stream/$room'
      fullPath: '/stream/$room'
      preLoaderRoute: typeof StreamRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$roomId': {
      id: '/stage/$roomId'
      path: '/stage/$roomId'
      fullPath: '/stage/$roomId'
      preLoaderRoute: typeof StageRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/social-links': {
      id: '/settings/social-links'
      path: '/social-links'
      fullPath: '/settings/social-links'
      preLoaderRoute: typeof SettingsSocialLinksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/music-media': {
      id: '/settings/music-media'
      path: '/music-media'
      fullPath: '/settings/music-media'
      preLoaderRoute: typeof SettingsMusicMediaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/merch': {
      id: '/settings/merch'
      path: '/merch'
      fullPath: '/settings/merch'
      preLoaderRoute: typeof SettingsMerchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/membership': {
      id: '/settings/membership'
      path: '/membership'
      fullPath: '/settings/membership'
      preLoaderRoute: typeof SettingsMembershipRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/events': {
      id: '/settings/events'
      path: '/events'
      fullPath: '/settings/events'
      preLoaderRoute: typeof SettingsEventsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connected-apps': {
      id: '/settings/connected-apps'
      path: '/connected-apps'
      fullPath: '/settings/connected-apps'
      preLoaderRoute: typeof SettingsConnectedAppsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/broadcast-help': {
      id: '/settings/broadcast-help'
      path: '/broadcast-help'
      fullPath: '/settings/broadcast-help'
      preLoaderRoute: typeof SettingsBroadcastHelpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/artist-info': {
      id: '/settings/artist-info'
      path: '/artist-info'
      fullPath: '/settings/artist-info'
      preLoaderRoute: typeof SettingsArtistInfoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/play/ranks': {
      id: '/play/ranks'
      path: '/play/ranks'
      fullPath: '/play/ranks'
      preLoaderRoute: typeof PlayRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$room': {
      id: '/play/$room'
      path: '/play/$room'
      fullPath: '/play/$room'
      preLoaderRoute: typeof PlayRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast/$broadcastId': {
      id: '/broadcast/$broadcastId'
      path: '/broadcast/$broadcastId'
      fullPath: '/broadcast/$broadcastId'
      preLoaderRoute: typeof BroadcastBroadcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/live-stream-music-twitch-youtube-facebook': {
      id: '/blog/live-stream-music-twitch-youtube-facebook'
      path: '/blog/live-stream-music-twitch-youtube-facebook'
      fullPath: '/blog/live-stream-music-twitch-youtube-facebook'
      preLoaderRoute: typeof BlogLiveStreamMusicTwitchYoutubeFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-live-stream-music': {
      id: '/blog/how-to-live-stream-music'
      path: '/blog/how-to-live-stream-music'
      fullPath: '/blog/how-to-live-stream-music'
      preLoaderRoute: typeof BlogHowToLiveStreamMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-artists-get-paid-for-streaming-music': {
      id: '/blog/how-artists-get-paid-for-streaming-music'
      path: '/blog/how-artists-get-paid-for-streaming-music'
      fullPath: '/blog/how-artists-get-paid-for-streaming-music'
      preLoaderRoute: typeof BlogHowArtistsGetPaidForStreamingMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/can-you-play-music-on-live-stream': {
      id: '/blog/can-you-play-music-on-live-stream'
      path: '/blog/can-you-play-music-on-live-stream'
      fullPath: '/blog/can-you-play-music-on-live-stream'
      preLoaderRoute: typeof BlogCanYouPlayMusicOnLiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/upgrade': {
      id: '/artist/upgrade'
      path: '/artist/upgrade'
      fullPath: '/artist/upgrade'
      preLoaderRoute: typeof ArtistUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vote-attempts': {
      id: '/admin/vote-attempts'
      path: '/vote-attempts'
      fullPath: '/admin/vote-attempts'
      preLoaderRoute: typeof AdminVoteAttemptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio-bookings': {
      id: '/admin/studio-bookings'
      path: '/studio-bookings'
      fullPath: '/admin/studio-bookings'
      preLoaderRoute: typeof AdminStudioBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/streams': {
      id: '/admin/streams'
      path: '/streams'
      fullPath: '/admin/streams'
      preLoaderRoute: typeof AdminStreamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merch': {
      id: '/admin/merch'
      path: '/merch'
      fullPath: '/admin/merch'
      preLoaderRoute: typeof AdminMerchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancellation-emails': {
      id: '/admin/cancellation-emails'
      path: '/cancellation-emails'
      fullPath: '/admin/cancellation-emails'
      preLoaderRoute: typeof AdminCancellationEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/block-bookings': {
      id: '/admin/block-bookings'
      path: '/block-bookings'
      fullPath: '/admin/block-bookings'
      preLoaderRoute: typeof AdminBlockBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/audience/$room': {
      id: '/play/audience/$room'
      path: '/play/audience/$room'
      fullPath: '/play/audience/$room'
      preLoaderRoute: typeof PlayAudienceRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast/$broadcastId/manage': {
      id: '/broadcast/$broadcastId/manage'
      path: '/manage'
      fullPath: '/broadcast/$broadcastId/manage'
      preLoaderRoute: typeof BroadcastBroadcastIdManageRouteImport
      parentRoute: typeof BroadcastBroadcastIdRoute
    }
    '/api/public/studio-booking': {
      id: '/api/public/studio-booking'
      path: '/api/public/studio-booking'
      fullPath: '/api/public/studio-booking'
      preLoaderRoute: typeof ApiPublicStudioBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout-cancellation-email': {
      id: '/api/public/checkout-cancellation-email'
      path: '/api/public/checkout-cancellation-email'
      fullPath: '/api/public/checkout-cancellation-email'
      preLoaderRoute: typeof ApiPublicCheckoutCancellationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/block-booking': {
      id: '/api/public/block-booking'
      path: '/api/public/block-booking'
      fullPath: '/api/public/block-booking'
      preLoaderRoute: typeof ApiPublicBlockBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhook': {
      id: '/api/public/shopify/webhook'
      path: '/api/public/shopify/webhook'
      fullPath: '/api/public/shopify/webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-payouts': {
      id: '/api/public/hooks/process-payouts'
      path: '/api/public/hooks/process-payouts'
      fullPath: '/api/public/hooks/process-payouts'
      preLoaderRoute: typeof ApiPublicHooksProcessPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlockBookingsRoute: typeof AdminBlockBookingsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCancellationEmailsRoute: typeof AdminCancellationEmailsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMerchRoute: typeof AdminMerchRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStreamsRoute: typeof AdminStreamsRoute
  AdminStudioBookingsRoute: typeof AdminStudioBookingsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoteAttemptsRoute: typeof AdminVoteAttemptsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlockBookingsRoute: AdminBlockBookingsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCancellationEmailsRoute: AdminCancellationEmailsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMerchRoute: AdminMerchRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStreamsRoute: AdminStreamsRoute,
  AdminStudioBookingsRoute: AdminStudioBookingsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoteAttemptsRoute: AdminVoteAttemptsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArtistInfoRoute: typeof SettingsArtistInfoRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsBroadcastHelpRoute: typeof SettingsBroadcastHelpRoute
  SettingsConnectedAppsRoute: typeof SettingsConnectedAppsRoute
  SettingsEventsRoute: typeof SettingsEventsRoute
  SettingsMembershipRoute: typeof SettingsMembershipRoute
  SettingsMerchRoute: typeof SettingsMerchRoute
  SettingsMusicMediaRoute: typeof SettingsMusicMediaRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSocialLinksRoute: typeof SettingsSocialLinksRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArtistInfoRoute: SettingsArtistInfoRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsBroadcastHelpRoute: SettingsBroadcastHelpRoute,
  SettingsConnectedAppsRoute: SettingsConnectedAppsRoute,
  SettingsEventsRoute: SettingsEventsRoute,
  SettingsMembershipRoute: SettingsMembershipRoute,
  SettingsMerchRoute: SettingsMerchRoute,
  SettingsMusicMediaRoute: SettingsMusicMediaRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSocialLinksRoute: SettingsSocialLinksRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface BroadcastBroadcastIdRouteChildren {
  BroadcastBroadcastIdManageRoute: typeof BroadcastBroadcastIdManageRoute
}

const BroadcastBroadcastIdRouteChildren: BroadcastBroadcastIdRouteChildren = {
  BroadcastBroadcastIdManageRoute: BroadcastBroadcastIdManageRoute,
}

const BroadcastBroadcastIdRouteWithChildren =
  BroadcastBroadcastIdRoute._addFileChildren(BroadcastBroadcastIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistDashboardRoute: ArtistDashboardRoute,
  ArtistSubmissionRoute: ArtistSubmissionRoute,
  ArtistsRoute: ArtistsRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CreatorAgreementRoute: CreatorAgreementRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  DeckRoute: DeckRoute,
  DiscoverRoute: DiscoverRoute,
  DmcaRoute: DmcaRoute,
  EarningsRoute: EarningsRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MicDropRoute: MicDropRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  OffTheBlockRoute: OffTheBlockRoute,
  PayoutsRoute: PayoutsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecordingsRoute: RecordingsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreamStudioRoute: StreamStudioRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  TunevioRoute: TunevioRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ASlugRoute: ASlugRoute,
  ArtistIdRoute: ArtistIdRoute,
  ArtistUpgradeRoute: ArtistUpgradeRoute,
  BlogCanYouPlayMusicOnLiveStreamRoute: BlogCanYouPlayMusicOnLiveStreamRoute,
  BlogHowArtistsGetPaidForStreamingMusicRoute:
    BlogHowArtistsGetPaidForStreamingMusicRoute,
  BlogHowToLiveStreamMusicRoute: BlogHowToLiveStreamMusicRoute,
  BlogLiveStreamMusicTwitchYoutubeFacebookRoute:
    BlogLiveStreamMusicTwitchYoutubeFacebookRoute,
  BroadcastBroadcastIdRoute: BroadcastBroadcastIdRouteWithChildren,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GenreSlugRoute: GenreSlugRoute,
  InviteCodeRoute: InviteCodeRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  PayReturnRoute: PayReturnRoute,
  PlayRoomRoute: PlayRoomRoute,
  PlayRanksRoute: PlayRanksRoute,
  StageRoomIdRoute: StageRoomIdRoute,
  StreamRoomRoute: StreamRoomRoute,
  TrackSlugRoute: TrackSlugRoute,
  UserIdRoute: UserIdRoute,
  VideosIdRoute: VideosIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  ApiPublicBlockBookingRoute: ApiPublicBlockBookingRoute,
  ApiPublicCheckoutCancellationEmailRoute:
    ApiPublicCheckoutCancellationEmailRoute,
  ApiPublicStudioBookingRoute: ApiPublicStudioBookingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PlayAudienceRoomRoute: PlayAudienceRoomRoute,
  ApiPublicHooksProcessPayoutsRoute: ApiPublicHooksProcessPayoutsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
