/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StreamStudioRouteImport } from './routes/stream-studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OffTheBlockRouteImport } from './routes/off-the-block'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MicDropRouteImport } from './routes/mic-drop'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveReviewRouteImport } from './routes/live-review'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as StreamRoomRouteImport } from './routes/stream.$room'
import { Route as SettingsSocialLinksRouteImport } from './routes/settings.social-links'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsMusicMediaRouteImport } from './routes/settings.music-media'
import { Route as SettingsMerchRouteImport } from './routes/settings.merch'
import { Route as SettingsMembershipRouteImport } from './routes/settings.membership'
import { Route as SettingsEventsRouteImport } from './routes/settings.events'
import { Route as SettingsConnectedAppsRouteImport } from './routes/settings.connected-apps'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsArtistInfoRouteImport } from './routes/settings.artist-info'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as PlayRoomRouteImport } from './routes/play.$room'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as LiveReviewSuccessRouteImport } from './routes/live-review.success'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as ArtistUpgradeRouteImport } from './routes/artist.upgrade'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStreamsRouteImport } from './routes/admin.streams'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMerchRouteImport } from './routes/admin.merch'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLiveQueueRouteImport } from './routes/admin.live-queue'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCancellationEmailsRouteImport } from './routes/admin.cancellation-emails'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PlayAudienceRoomRouteImport } from './routes/play.audience.$room'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicStudioBookingRouteImport } from './routes/api/public/studio-booking'
import { Route as ApiPublicCheckoutCancellationEmailRouteImport } from './routes/api/public/checkout-cancellation-email'
import { Route as ApiPublicBlockBookingRouteImport } from './routes/api/public/block-booking'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify/webhook'
import { Route as ApiPublicShopifyInstallRouteImport } from './routes/api/public/shopify/install'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamStudioRoute = StreamStudioRouteImport.update({
  id: '/stream-studio',
  path: '/stream-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OffTheBlockRoute = OffTheBlockRouteImport.update({
  id: '/off-the-block',
  path: '/off-the-block',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MicDropRoute = MicDropRouteImport.update({
  id: '/mic-drop',
  path: '/mic-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveReviewRoute = LiveReviewRouteImport.update({
  id: '/live-review',
  path: '/live-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoomRoute = StreamRoomRouteImport.update({
  id: '/stream/$room',
  path: '/stream/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSocialLinksRoute = SettingsSocialLinksRouteImport.update({
  id: '/social-links',
  path: '/social-links',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMusicMediaRoute = SettingsMusicMediaRouteImport.update({
  id: '/music-media',
  path: '/music-media',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMerchRoute = SettingsMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMembershipRoute = SettingsMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEventsRoute = SettingsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectedAppsRoute = SettingsConnectedAppsRouteImport.update({
  id: '/connected-apps',
  path: '/connected-apps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArtistInfoRoute = SettingsArtistInfoRouteImport.update({
  id: '/artist-info',
  path: '/artist-info',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const PlayRoomRoute = PlayRoomRouteImport.update({
  id: '/play/$room',
  path: '/play/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveReviewSuccessRoute = LiveReviewSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LiveReviewRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistUpgradeRoute = ArtistUpgradeRouteImport.update({
  id: '/artist/upgrade',
  path: '/artist/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStreamsRoute = AdminStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchRoute = AdminMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveQueueRoute = AdminLiveQueueRouteImport.update({
  id: '/live-queue',
  path: '/live-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancellationEmailsRoute = AdminCancellationEmailsRouteImport.update({
  id: '/cancellation-emails',
  path: '/cancellation-emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PlayAudienceRoomRoute = PlayAudienceRoomRouteImport.update({
  id: '/play/audience/$room',
  path: '/play/audience/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStudioBookingRoute = ApiPublicStudioBookingRouteImport.update({
  id: '/api/public/studio-booking',
  path: '/api/public/studio-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutCancellationEmailRoute =
  ApiPublicCheckoutCancellationEmailRouteImport.update({
    id: '/api/public/checkout-cancellation-email',
    path: '/api/public/checkout-cancellation-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlockBookingRoute = ApiPublicBlockBookingRouteImport.update({
  id: '/api/public/block-booking',
  path: '/api/public/block-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify/webhook',
  path: '/api/public/shopify/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyInstallRoute = ApiPublicShopifyInstallRouteImport.update({
  id: '/api/public/shopify/install',
  path: '/api/public/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/live-review': typeof LiveReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live-review/success': typeof LiveReviewSuccessRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stream/$room': typeof StreamRoomRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/play/': typeof PlayIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/artists': typeof ArtistsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/live-review': typeof LiveReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live-review/success': typeof LiveReviewSuccessRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stream/$room': typeof StreamRoomRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin': typeof AdminIndexRoute
  '/play': typeof PlayIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/earnings': typeof EarningsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/live-review': typeof LiveReviewRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/mic-drop': typeof MicDropRoute
  '/notifications': typeof NotificationsRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream-studio': typeof StreamStudioRoute
  '/studio': typeof StudioRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cancellation-emails': typeof AdminCancellationEmailsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$code': typeof InviteCodeRoute
  '/live-review/success': typeof LiveReviewSuccessRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/pay/return': typeof PayReturnRoute
  '/play/$room': typeof PlayRoomRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artist-info': typeof SettingsArtistInfoRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connected-apps': typeof SettingsConnectedAppsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/membership': typeof SettingsMembershipRoute
  '/settings/merch': typeof SettingsMerchRoute
  '/settings/music-media': typeof SettingsMusicMediaRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/stream/$room': typeof StreamRoomRoute
  '/user/$id': typeof UserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/play/': typeof PlayIndexRoute
  '/api/public/block-booking': typeof ApiPublicBlockBookingRoute
  '/api/public/checkout-cancellation-email': typeof ApiPublicCheckoutCancellationEmailRoute
  '/api/public/studio-booking': typeof ApiPublicStudioBookingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/play/audience/$room': typeof PlayAudienceRoomRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/deck'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/live'
    | '/live-review'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/notifications'
    | '/off-the-block'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/unsubscribe'
    | '/videos'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/live-queue'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/invite/$code'
    | '/live-review/success'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stream/$room'
    | '/user/$id'
    | '/videos/$id'
    | '/admin/'
    | '/play/'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/artists'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/deck'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/live'
    | '/live-review'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/notifications'
    | '/off-the-block'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/unsubscribe'
    | '/videos'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/live-queue'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/invite/$code'
    | '/live-review/success'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stream/$room'
    | '/user/$id'
    | '/videos/$id'
    | '/admin'
    | '/play'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/deck'
    | '/earnings'
    | '/events'
    | '/forgot-password'
    | '/live'
    | '/live-review'
    | '/login'
    | '/messages'
    | '/mic-drop'
    | '/notifications'
    | '/off-the-block'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/stream-studio'
    | '/studio'
    | '/unsubscribe'
    | '/videos'
    | '/admin/analytics'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/cancellation-emails'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/live-queue'
    | '/admin/login'
    | '/admin/merch'
    | '/admin/messages'
    | '/admin/ops'
    | '/admin/payouts'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/admin/users'
    | '/artist/$id'
    | '/artist/upgrade'
    | '/checkout/cancel'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/invite/$code'
    | '/live-review/success'
    | '/pay/$bookingId'
    | '/pay/return'
    | '/play/$room'
    | '/settings/appearance'
    | '/settings/artist-info'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/events'
    | '/settings/membership'
    | '/settings/merch'
    | '/settings/music-media'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/social-links'
    | '/stream/$room'
    | '/user/$id'
    | '/videos/$id'
    | '/admin/'
    | '/play/'
    | '/api/public/block-booking'
    | '/api/public/checkout-cancellation-email'
    | '/api/public/studio-booking'
    | '/lovable/email/suppression'
    | '/play/audience/$room'
    | '/api/public/payments/webhook'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DeckRoute: typeof DeckRoute
  EarningsRoute: typeof EarningsRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveRoute: typeof LiveRoute
  LiveReviewRoute: typeof LiveReviewRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MicDropRoute: typeof MicDropRoute
  NotificationsRoute: typeof NotificationsRoute
  OffTheBlockRoute: typeof OffTheBlockRoute
  ProfileRoute: typeof ProfileRoute
  RecordingsRoute: typeof RecordingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreamStudioRoute: typeof StreamStudioRoute
  StudioRoute: typeof StudioRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VideosRoute: typeof VideosRouteWithChildren
  ArtistIdRoute: typeof ArtistIdRoute
  ArtistUpgradeRoute: typeof ArtistUpgradeRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteCodeRoute: typeof InviteCodeRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  PayReturnRoute: typeof PayReturnRoute
  PlayRoomRoute: typeof PlayRoomRoute
  StreamRoomRoute: typeof StreamRoomRoute
  UserIdRoute: typeof UserIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ApiPublicBlockBookingRoute: typeof ApiPublicBlockBookingRoute
  ApiPublicCheckoutCancellationEmailRoute: typeof ApiPublicCheckoutCancellationEmailRoute
  ApiPublicStudioBookingRoute: typeof ApiPublicStudioBookingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PlayAudienceRoomRoute: typeof PlayAudienceRoomRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyInstallRoute: typeof ApiPublicShopifyInstallRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream-studio': {
      id: '/stream-studio'
      path: '/stream-studio'
      fullPath: '/stream-studio'
      preLoaderRoute: typeof StreamStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-the-block': {
      id: '/off-the-block'
      path: '/off-the-block'
      fullPath: '/off-the-block'
      preLoaderRoute: typeof OffTheBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mic-drop': {
      id: '/mic-drop'
      path: '/mic-drop'
      fullPath: '/mic-drop'
      preLoaderRoute: typeof MicDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-review': {
      id: '/live-review'
      path: '/live-review'
      fullPath: '/live-review'
      preLoaderRoute: typeof LiveReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$room': {
      id: '/stream/$room'
      path: '/stream/$room'
      fullPath: '/stream/$room'
      preLoaderRoute: typeof StreamRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/social-links': {
      id: '/settings/social-links'
      path: '/social-links'
      fullPath: '/settings/social-links'
      preLoaderRoute: typeof SettingsSocialLinksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/music-media': {
      id: '/settings/music-media'
      path: '/music-media'
      fullPath: '/settings/music-media'
      preLoaderRoute: typeof SettingsMusicMediaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/merch': {
      id: '/settings/merch'
      path: '/merch'
      fullPath: '/settings/merch'
      preLoaderRoute: typeof SettingsMerchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/membership': {
      id: '/settings/membership'
      path: '/membership'
      fullPath: '/settings/membership'
      preLoaderRoute: typeof SettingsMembershipRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/events': {
      id: '/settings/events'
      path: '/events'
      fullPath: '/settings/events'
      preLoaderRoute: typeof SettingsEventsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connected-apps': {
      id: '/settings/connected-apps'
      path: '/connected-apps'
      fullPath: '/settings/connected-apps'
      preLoaderRoute: typeof SettingsConnectedAppsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/artist-info': {
      id: '/settings/artist-info'
      path: '/artist-info'
      fullPath: '/settings/artist-info'
      preLoaderRoute: typeof SettingsArtistInfoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/play/$room': {
      id: '/play/$room'
      path: '/play/$room'
      fullPath: '/play/$room'
      preLoaderRoute: typeof PlayRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-review/success': {
      id: '/live-review/success'
      path: '/success'
      fullPath: '/live-review/success'
      preLoaderRoute: typeof LiveReviewSuccessRouteImport
      parentRoute: typeof LiveReviewRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/upgrade': {
      id: '/artist/upgrade'
      path: '/artist/upgrade'
      fullPath: '/artist/upgrade'
      preLoaderRoute: typeof ArtistUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/streams': {
      id: '/admin/streams'
      path: '/streams'
      fullPath: '/admin/streams'
      preLoaderRoute: typeof AdminStreamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merch': {
      id: '/admin/merch'
      path: '/merch'
      fullPath: '/admin/merch'
      preLoaderRoute: typeof AdminMerchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-queue': {
      id: '/admin/live-queue'
      path: '/live-queue'
      fullPath: '/admin/live-queue'
      preLoaderRoute: typeof AdminLiveQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancellation-emails': {
      id: '/admin/cancellation-emails'
      path: '/cancellation-emails'
      fullPath: '/admin/cancellation-emails'
      preLoaderRoute: typeof AdminCancellationEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/play/audience/$room': {
      id: '/play/audience/$room'
      path: '/play/audience/$room'
      fullPath: '/play/audience/$room'
      preLoaderRoute: typeof PlayAudienceRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/studio-booking': {
      id: '/api/public/studio-booking'
      path: '/api/public/studio-booking'
      fullPath: '/api/public/studio-booking'
      preLoaderRoute: typeof ApiPublicStudioBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout-cancellation-email': {
      id: '/api/public/checkout-cancellation-email'
      path: '/api/public/checkout-cancellation-email'
      fullPath: '/api/public/checkout-cancellation-email'
      preLoaderRoute: typeof ApiPublicCheckoutCancellationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/block-booking': {
      id: '/api/public/block-booking'
      path: '/api/public/block-booking'
      fullPath: '/api/public/block-booking'
      preLoaderRoute: typeof ApiPublicBlockBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhook': {
      id: '/api/public/shopify/webhook'
      path: '/api/public/shopify/webhook'
      fullPath: '/api/public/shopify/webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/install': {
      id: '/api/public/shopify/install'
      path: '/api/public/shopify/install'
      fullPath: '/api/public/shopify/install'
      preLoaderRoute: typeof ApiPublicShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCancellationEmailsRoute: typeof AdminCancellationEmailsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLiveQueueRoute: typeof AdminLiveQueueRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMerchRoute: typeof AdminMerchRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStreamsRoute: typeof AdminStreamsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCancellationEmailsRoute: AdminCancellationEmailsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLiveQueueRoute: AdminLiveQueueRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMerchRoute: AdminMerchRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStreamsRoute: AdminStreamsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LiveReviewRouteChildren {
  LiveReviewSuccessRoute: typeof LiveReviewSuccessRoute
}

const LiveReviewRouteChildren: LiveReviewRouteChildren = {
  LiveReviewSuccessRoute: LiveReviewSuccessRoute,
}

const LiveReviewRouteWithChildren = LiveReviewRoute._addFileChildren(
  LiveReviewRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArtistInfoRoute: typeof SettingsArtistInfoRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsConnectedAppsRoute: typeof SettingsConnectedAppsRoute
  SettingsEventsRoute: typeof SettingsEventsRoute
  SettingsMembershipRoute: typeof SettingsMembershipRoute
  SettingsMerchRoute: typeof SettingsMerchRoute
  SettingsMusicMediaRoute: typeof SettingsMusicMediaRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSocialLinksRoute: typeof SettingsSocialLinksRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArtistInfoRoute: SettingsArtistInfoRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsConnectedAppsRoute: SettingsConnectedAppsRoute,
  SettingsEventsRoute: SettingsEventsRoute,
  SettingsMembershipRoute: SettingsMembershipRoute,
  SettingsMerchRoute: SettingsMerchRoute,
  SettingsMusicMediaRoute: SettingsMusicMediaRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSocialLinksRoute: SettingsSocialLinksRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DeckRoute: DeckRoute,
  EarningsRoute: EarningsRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveRoute: LiveRoute,
  LiveReviewRoute: LiveReviewRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MicDropRoute: MicDropRoute,
  NotificationsRoute: NotificationsRoute,
  OffTheBlockRoute: OffTheBlockRoute,
  ProfileRoute: ProfileRoute,
  RecordingsRoute: RecordingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreamStudioRoute: StreamStudioRoute,
  StudioRoute: StudioRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VideosRoute: VideosRouteWithChildren,
  ArtistIdRoute: ArtistIdRoute,
  ArtistUpgradeRoute: ArtistUpgradeRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteCodeRoute: InviteCodeRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  PayReturnRoute: PayReturnRoute,
  PlayRoomRoute: PlayRoomRoute,
  StreamRoomRoute: StreamRoomRoute,
  UserIdRoute: UserIdRoute,
  PlayIndexRoute: PlayIndexRoute,
  ApiPublicBlockBookingRoute: ApiPublicBlockBookingRoute,
  ApiPublicCheckoutCancellationEmailRoute:
    ApiPublicCheckoutCancellationEmailRoute,
  ApiPublicStudioBookingRoute: ApiPublicStudioBookingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PlayAudienceRoomRoute: PlayAudienceRoomRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyInstallRoute: ApiPublicShopifyInstallRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
