/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as OffTheBlockRouteImport } from './routes/off-the-block'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const OffTheBlockRoute = OffTheBlockRouteImport.update({
  id: '/off-the-block',
  path: '/off-the-block',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/deck': typeof DeckRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/studio': typeof StudioRoute
  '/videos': typeof VideosRouteWithChildren
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/deck': typeof DeckRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/studio': typeof StudioRoute
  '/videos': typeof VideosRouteWithChildren
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/deck': typeof DeckRoute
  '/off-the-block': typeof OffTheBlockRoute
  '/studio': typeof StudioRoute
  '/videos': typeof VideosRouteWithChildren
  '/videos/$id': typeof VideosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/deck'
    | '/off-the-block'
    | '/studio'
    | '/videos'
    | '/videos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/deck'
    | '/off-the-block'
    | '/studio'
    | '/videos'
    | '/videos/$id'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/deck'
    | '/off-the-block'
    | '/studio'
    | '/videos'
    | '/videos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  DeckRoute: typeof DeckRoute
  OffTheBlockRoute: typeof OffTheBlockRoute
  StudioRoute: typeof StudioRoute
  VideosRoute: typeof VideosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-the-block': {
      id: '/off-the-block'
      path: '/off-the-block'
      fullPath: '/off-the-block'
      preLoaderRoute: typeof OffTheBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
  }
}

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  DeckRoute: DeckRoute,
  OffTheBlockRoute: OffTheBlockRoute,
  StudioRoute: StudioRoute,
  VideosRoute: VideosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
